# Generated by Django 5.1 on 2024-08-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model',
            new_name='Order',
        ),
    ]
